name: Delete application

on:
  delete:

jobs:
  delete:
    name: delete
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: say
        run: echo "DELETE the ${{ github.event.ref }} branch!"