name: Deploy application

on:
  push:
  delete:

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: say
        run: echo "Hello from the ${{ github.ref_name }} branch!"